services:
  psql:
    hostname: ${HOST_POSTGRES}
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
    networks:
      - peresvet

networks:
  peresvet:
    driver: bridge
    ipam:
      config:
          - subnet: 10.66.0.0/16
            gateway: 10.66.0.1

