version: '3.9'

services:
  psql_load_tests:
    hostname: psql_load_tests
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # command: postgres -c max_connections=1000 -c shared_buffers=4GB
    ports:
      - 5432:5432
    volumes:
      - ~/psql_load_tests:/var/lib/postgresql/data
      - ./config/psql/postgresql.conf:/etc/postgresql/postgresql.conf
