version: '3.9'

services:
  data_storages_all:
    hostname: dataStorages_all
    build:
      context: ../..
      dockerfile: docker/docker-files/dataStorages/Dockerfile.dataStorages.all.debug

    environment:
      TZ: ${TIME_ZONE}
      DEBUG_SVC: ${debug_svc}

    ports:
      - 82:82
      - 5678:5678

    volumes:
      - ./logs/dataStorages.all/api_crud/:/usr/src/dataStorages_api_crud/log/:rw
      - ./logs/dataStorages.all/model_crud/:/usr/src/dataStorages_model_crud/log/:rw
      - ./logs/dataStorages.all/app_psql/:/usr/src/dataStorages_app_psql/log/:rw
      - ./logs/dataStorages.all/app_vm/:/usr/src/dataStorages_app_vm/log/:rw
